# Change these first
owner: FormulaRossa # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Lean Schuler
    url: https://www.leanschuler.ch
  - name: What Homework Homepage
    url: https://www.whathomework.ch
  - name: What Homework App
    url: https://app.whathomework.ch

assignees:
  - FormulaRossa


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.leanschuler.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/FormulaRossa/status/master/assets/logo.png
  name: Status
  theme: light
  introTitle: "Welcome to Lean Schuler's status page!"
  introMessage: "On this page you'll find information about the status of services and applications provided by Lean Schuler."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
